import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import StoreProvider from '@/components/providers/StoreProvider';
import './globals.css';
import Header from '@/components/header/Header';
import clsx from 'clsx';

const poppins = Poppins({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nimble test task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={clsx(poppins.className, 'bg-bgBlack')}>
          <div className="wrapper">
            <Header />
            <main className="mt-12">{children}</main>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
